name = "EHTNCDBase"
uuid = "0d1a6071-c6ae-40ce-b68e-43bf1c0beb66"
authors = ["Kazunori Akiyama"]
version = "0.1.0"

[deps]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
julia = "1.7.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
